### ISSUE TITLE
Alias for --output-path isn't working for the build command in 0.1.5 

### ISSUE THREAD

**Issue by mihai-scurtu** [ember-cli/ember-cli#2943]
When trying to build using `ember build -e foo -o dist-foo/` I get the following error:

```
The option '--outputPath' is not supported by the build command. Run `ember build --help` for a list of supported options.
Build failed.
Arguments to path.resolve must be strings
```

It works fine with the full argument `--output-path`

**Comment by trabus** [comment]
This is definitely a bug with the command options validation. I'll look into it.

**Comment by rwjblue** [comment]
@trabus - Should be fixed by #2951.

**Comment by trabus** [comment]
@rwjblue the unsupported option warning is actually still an issue for any options with a dash in the name. I've got a PR coming shortly.
