### ISSUE TITLE
ember build/serve causes AssertionError: false == true

### ISSUE THREAD

**Issue by wecc** [ember-cli/ember-cli#2968]
Just updated to 0.1.6 and created a brand new project and now I'm unable to run/build it.

```
=> ember build
version: 0.1.6
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: my-app/app.js
false == true
AssertionError: false == true
    at Visitor.PVp.visitWithoutReset (/Users/Christoffer/Code/my-app/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:135:12)
    at Visitor.PVp.visit (/Users/Christoffer/Code/my-app/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:117:21)
    at Function.transform (/Users/Christoffer/Code/my-app/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/node_modules/regenerator/lib/visit.js:31:18)
    at transform (/Users/Christoffer/Code/my-app/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/lib/index.js:86:23)
    at compile (/Users/Christoffer/Code/my-app/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext/lib/index.js:33:9)
    at EsnextFilter.processString (/Users/Christoffer/Code/my-app/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/index.js:41:16)
    at EsnextFilter.Filter.processFile (/Users/Christoffer/Code/my-app/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/index.js:136:31)
    at Promise.resolve.then.catch.err.file (/Users/Christoffer/Code/my-app/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/index.js:82:21)
    at $$$internal$$tryCatch (/Users/Christoffer/Code/my-app/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/Christoffer/Code/my-app/node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:502:17)
```

I've cleared NPM cache and re-installed using the instructions at http://www.ember-cli.com/#project-update, still no luck.

```
=> ember --version
version: 0.1.6
node: 0.10.33
npm: 2.1.8
```

**Comment by wecc** [comment]
It looks like this was introduced by https://github.com/facebook/regenerator/commit/2be435b3113d9c4709ad5cf60290280964c0154f

Manually checking out the previous commit of the regenerator library (used by esnext, used by broccoli-esnext, used by ember-cli-esnext) makes it all work again.

**Comment by listepo** [comment]
I have the exact same problem and `ember server`

**Comment by vasilakisfil** [comment]
same problem here for both ember-cli 0.1.4 and 0.1.5.

**Comment by oriSomething** [comment]
same here, 0.1.4 and 0.1.6

**Comment by jaydev** [comment]
+1, using ember-cli 0.1.5

btw, this command installs the correct working version of regenerator once you navigate to the esnext folder:
`npm install 'git+https://github.com/facebook/regenerator.git#45829598be68fa4cb10f86b5ca13aa7284aa6bc8'`

pasting it here because it took me a little bit of googling to figure out how to install an exact revision via npm.

**Comment by oriSomething** [comment]
i replaced esnext with 6to5 (https://github.com/stefanpenner/ember-cli-6to5)
and i got `let` support as a bonus, and everything seems to work fine

**Comment by listepo** [comment]
add to package.json 
`"scripts": {
...
"postinstall":"bash ./regenerator.sh"
...}`
regenerator.sh
`#!/bin/bash
cd ./node_modules/ember-cli-esnext/node_modules/broccoli-esnext/node_modules/esnext
npm install 'git+https://github.com/facebook/regenerator.git#45829598be68fa4cb10f86b5ca13aa7284aa6bc8'`

**Comment by broerse** [comment]
same here in 0.1.6

**Comment by bobbysciacchitano** [comment]
Replacing it with ember-cli-6to5 seems to solve this issue. Thanks.

**Comment by toranb** [comment]
replaced with ember-cli-6to5 and all is legit

thanks for the quick issue/resolution everyone!

**Comment by williamsbdev** [comment]
+1 on the ember-cli-6to5! (specifically version 0.2.1).

Thanks @bobbysciacchitano!

**Comment by zyllorion** [comment]
Note to all - check your app runs ok in ie8 if you switch to ember-cli-6to5, I can't verify it definitely breaks things but I get a different error to the one I was trying to resolve before.

**Comment by oriSomething** [comment]
@zyllorion

6to5 doesn't support IE8 at least without proper shims.
i think it's one of the reasons it's not the default by ember-cli yet.

**Comment by stefanpenner** [comment]
well then, i suppose i should just merge: https://github.com/ember-cli/ember-cli/pull/2960 :P

**Comment by zyllorion** [comment]
@oriSomething @stefanpenner if we need to now include shims for ie8 support, there needs to be documentation for it as manually adding them seemed to cause conflicts last time I tried.

**Comment by eibrahim** [comment]
We are having the same problem.  The weird thing is that it works for me but not my coworker.  Not sure what's different for us.  We tried nuking node_modules, bower_component, cleaning the cache.  nothing worked for him.  I can't reproduce it on my machine.  He is on linux and I am on a mac - not sure if that's the case

**Comment by zyllorion** [comment]
As mentioned https://github.com/ember-cli/ember-cli/issues/2968#issuecomment-69720456
```
npm install --save-dev 'git+https://github.com/facebook/regenerator.git#45829598be68fa4cb10f86b5ca13aa7284aa6bc8'
```

**Comment by listepo** [comment]
ember-cli-6to5 better :+1:

**Comment by kellyselden** [comment]
thank you all for this workaround

**Comment by esbanarango** [comment]
:+1:

**Comment by wecc** [comment]
Confirm this is solved by https://github.com/ember-cli/ember-cli/releases/tag/v0.1.7

**Comment by jakcharlton** [comment]
Having done everything suggested in this thread, I still get the error ... 

Upgrade to 0.1.7 didn't resole.

Tried npm install 'git+https://github.com/facebook/regenerator.git#45829598be68fa4cb10f86b5ca13aa7284aa6bc8' - didn't resolve

Tried npm install --save-dev ember-cli-6to5 - didn't resolve


Anything else to fix other than the ember-cli instruction for upgrading from here?  http://www.ember-cli.com/

**Comment by jakecraige** [comment]
@jakcharlton Sounds like something is up with your internet. [ember-cli-6to5](https://www.npmjs.com/package/ember-cli-6to5) definitely exists as you can see by that link

**Comment by jakcharlton** [comment]
@jakecraige "didnt resolve" = "didnt resolve the problem" :)

Figured it out now ... for anyone else who still hits the problem, check that

**Comment by jakecraige** [comment]
@jakcharlton hahaha my bad. glad you figured it out
