### ISSUE TITLE
Can't build for environment production

### ISSUE THREAD

**Issue by Kuzirashi** [ember-cli/ember-cli#2981]
When I was using ember-cli@0.1.2 everything was working fine, but now, using 0.1.7 I can't build my application for production environment:
~~~~
$ ember build --environment=production
version: 0.1.7
Building.(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
# [XXX times same warning]
RangeError: Maximum call stack size exceeded
$
~~~~
When using `ember serve` everything works.
package.json:
~~~~
{
  "name": "myAppName",
  "version": "0.0.0",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "https://github.com/ember-cli/ember-cli",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "broccoli-static-compiler": "^0.2.1",
    "ember-cli": "0.1.7",
    "ember-cli-6to5": "0.2.1",
    "ember-cli-coffeescript": "^0.6.0",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-datepicker": "^1.3.0",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-htmlbars": "^0.5.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.1.2",
    "ember-cli-sass": "3.0.3",
    "ember-data": "1.0.0-beta.14",
    "ember-export-application-global": "^1.0.0",
    "ember-validations": "^2.0.0-alpha.1",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  },
  "dependencies": {
    "ember-cli-lightbox": "^0.1.9",
    "ember-droplet": "^0.9.1"
  }
}
~~~~

bower.json:
~~~~
{
  "name": "myAppName",
  "dependencies": {
    "handlebars": "2.0.0",
    "jquery": "^1.11.1",
    "ember": "1.9.1",
    "ember-data": "~1.0.0-beta.14.1",
    "ember-resolver": "~0.1.11",
    "loader.js": "ember-cli/loader.js#1.0.1",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.4",
    "qunit": "~1.15.0",
    "ember-forms": "~0.4.0",
    "jquery-cookie": "~1.4.1",
    "ember-droplet": "~0.8.7",
    "timeago": "~1.4.1",
    "jquery-autosize": "~1.18.17",
    "maphilight": "~1.3.0",
    "lightbox": "2.7.1",
    "fancybox": "~2.1.5",
    "bootstrap-sass-official": "~3.3.1",
    "font-awesome": "~4.2.0",
    "bootstrap-social": "~4.8.0",
    "jquery-ui": "~1.11.2",
    "pikaday": "~1.2.0",
    "moment": "~2.8.4"
  },
  "resolutions": {
    "handlebars": "2.0.0",
    "ember": "1.9.1"
  }
}
~~~~
Brocfile.js(I tried with clean Brocfile.js and same thing happens):
~~~~
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var pickFiles = require('broccoli-static-compiler');

var app = new EmberApp();
app.import('bower_components/ember-data/ember-data.js.map', { destDir: 'assets' }); 

app.import('bower_components/ember-forms/dist/globals/main.js');

var bootstrapFonts = pickFiles('bower_components/bootstrap-sass-official/assets/fonts/bootstrap', {
  srcDir: '/',
  destDir: '/fonts/bootstrap'
});

app.import('bower_components/bootstrap-sass-official/assets/javascripts/bootstrap/modal.js');

var fontAwesomeFonts = pickFiles('bower_components/font-awesome/fonts', {
  srcDir: '/',
  destDir: '/fonts'
});

app.import('bower_components/jquery-cookie/jquery.cookie.js');
app.import('bower_components/ember-droplet/dist/ember-droplet.min.js');

app.import('bower_components/timeago/jquery.timeago.js')
app.import('bower_components/timeago/locales/jquery.timeago.pl.js')

app.import('bower_components/jquery-autosize/jquery.autosize.min.js')

app.import('bower_components/maphilight/jquery.maphilight.min.js')

app.import('bower_components/fancybox/source/jquery.fancybox.css');
app.import('bower_components/fancybox/source/jquery.fancybox.pack.js')

var fancyFiles = pickFiles('bower_components/fancybox', {
    srcDir: '/source',
    files: ['**/*.png', '**/*.gif'],
    destDir: '/assets'
});

app.import('bower_components/jquery-ui/ui/core.js');
app.import('bower_components/jquery-ui/ui/widget.js');
app.import('bower_components/jquery-ui/ui/mouse.js');
app.import('bower_components/jquery-ui/ui/draggable.js');
app.import('bower_components/jquery-ui/ui/droppable.js');
app.import('bower_components/jquery-ui/ui/sortable.js');

app.import('vendor/microfiche.js');
app.import('vendor/pikaday-time.js');

var index = app.legacyFilesToAppend.indexOf('bower_components/handlebars/handlebars.runtime.js');
if(index) {
  app.legacyFilesToAppend[index] = 'bower_components/handlebars/handlebars.js';
}

// Use `app.import` to add additional libraries to the generated
// output files.
//
// If you need to use different assets in different
// environments, specify an object as the first parameter. That
// object's keys should be the environment name and the values
// should be the asset to use in that environment.
//
// If the library that you are including contains AMD or ES6
// modules that you would like to import into your application
// please specify an object with the list of modules as keys
// along with the exports of each module as its value.

module.exports = app.toTree([bootstrapFonts, fontAwesomeFonts, fancyFiles]);
~~~~

**Comment by stefanpenner** [comment]
can you provide an example app that demonstrates this issue. It would save us much time getting your project setup.

**Comment by nragaz** [comment]
I created a new project with this package.json, bower.json and Brocfile.js and can't reproduce the error on npm 2.1.18 and node 0.10.35.

My team is having the same issue (with 0.1.6) but because it is internal I unfortunately can't provide it to reproduce.

It is intermittent, even on the same machine -- ember build will pass once then fail the next time. Literally the worst.

**Comment by dfreeman** [comment]
I'm also hitting this with 0.1.7, but haven't managed to work it down to a useful reproduction case yet (working on it).

With `--throw-deprecation`, though, I can at least point at something `broccoli-sourcemap-concat` is doing with `combined-stream` as a likely source.

```
Error: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
    at maxTickWarn (node.js:379:15)
    at process._nextTick [as _currentTickHandler] (node.js:484:9)
    at process.nextTick (node.js:335:15)
    at ReadStream.stream.resume (_stream_readable.js:780:15)
    at DelayedStream.resume (/Users/dfreeman/Checkouts/app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:50:15)
    at DelayedStream.pipe (/Users/dfreeman/Checkouts/app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:68:8)
    at CombinedStream._pipeNext (/Users/dfreeman/Checkouts/app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/combined-stream/lib/combined_stream.js:101:12)
```

**Comment by nragaz** [comment]
We're getting something similar:

````
     [exec] Trace: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
     [exec]     at maxTickWarn (node.js:404:17)
     [exec]     at process._nextTick [as _currentTickHandler] (node.js:507:9)
     [exec]     at process.nextTick (node.js:358:15)
     [exec]     at endReadable (_stream_readable.js:939:13)
     [exec]     at ReadStream.Readable.read (_stream_readable.js:372:5)
     [exec]     at ReadStream.<anonymous> (_stream_readable.js:764:45)
     [exec]     at ReadStream.emit (events.js:92:17)
     [exec]     at ReadStream.source.emit (/vagrant/front-end/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:30:21)
     [exec]     at _stream_readable.js:782:16
     [exec]     at process._tickCallback (node.js:442:13)
````

**Comment by dfreeman** [comment]
Another data point for debugging (/workaround): I only see this happen when sourcemaps are disabled, which explains why it was only happening with the production build.

**Comment by stefanpenner** [comment]
this sounds like the node next-tick issue in 0.10.x that is fixed in 0.11.x

@ef4 it appears to be related to some of the stream stuff in broccoli-sourcemap-concat, i am unsure if a work around is simple or not, any thoughts?  It may be similar issue to one we worked-around in rsvp: https://github.com/tildeio/rsvp.js/pull/337

**Comment by Kuzirashi** [comment]
Same error in 0.1.9.

**Comment by sandstrom** [comment]
Another data point on dfreeman's observation (https://github.com/ember-cli/ember-cli/issues/2981#issuecomment-70035312).

**Comment by ef4** [comment]
Given the symptoms, my hunch is that the problem is related to this:

https://github.com/ef4/broccoli-sourcemap-concat/blob/73b58ec1fe18b2ad5f72c177e0d76360415435d7/simple-concat.js#L105

@stefanpenner should it be safe to use RSVP.async this way?

**Comment by stefanpenner** [comment]
@ef4 not in node 0.10.x until i release a new RSVP.

(node 0.10.x is broken)

relevant PR https://github.com/tildeio/rsvp.js/pull/337

**Comment by sandstrom** [comment]
@ef4 Sorry to poke, but is this something originating from broccoli-sourcemap-concat?

We're using the workaround of forcing source maps in production (to avoid the `Recursive process.nextTick detected` error).

**Comment by stefanpenner** [comment]
@fivetanley got any free time to cut a new RSVP? I likely wont have much time till after I move (this weekend)

**Comment by sandstrom** [comment]
*For anyone watching this:* @fivetanley cut a new version just now: https://github.com/tildeio/rsvp.js/commit/5cfda6229538e17a740f9f3758868672640c15e3

**Comment by stefanpenner** [comment]
@fivetanley <3

**Comment by stefanpenner** [comment]
fixed now that rsvp is relased.

**Comment by peterjmit** [comment]
:tada: :+1:

**Comment by sandstrom** [comment]
Perhaps I'm doing something wrong, but I still see the `(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.` error.

Have I misunderstood something?

    $ npm ls | grep rsvp
    │ │ └── rsvp@3.0.17
    │ │ └── rsvp@3.0.17
    │ │ ├── rsvp@3.0.17
    │ │ └── rsvp@3.0.17
    │ │ └── rsvp@3.0.17
    │ │ ├── rsvp@3.0.17
    │ │ └── rsvp@3.0.17
    │ │ └── rsvp@3.0.17
    │ │ └── rsvp@3.0.17
    │ │ └── rsvp@3.0.17
    │ ├── rsvp@3.0.17
    └── rsvp@3.0.17

    $ ember --version
    version: 0.1.15
    node: 0.10.32
    npm: 2.1.8

**Comment by stefanpenner** [comment]
strange, maybe it something else?  @sandstrom if you can update to iojs or node 0.12.x or even 0.11.x the problem should be gone as it is fixed in node.

**Comment by sandstrom** [comment]
I gave up on figuring out why and went with node 0.12.

Thanks Stefan!

**Comment by stefanpenner** [comment]
> I gave up on figuring out why and went with node 0.12.
> 
> Thanks Stefan!


:+1:

**Comment by anpenava** [comment]
@Kuzirashi are there any potential risks of performance issues on production with your workaround ?

**Comment by Kuzirashi** [comment]
@anpenava You will have generated source maps. I believe that unless you open Chrome Dev Tools you shouldn't notice any performance regressions.
