### ISSUE TITLE
[0.2.3] Unit test blueprint mistaken as actual test

### ISSUE THREAD

**Issue by mihai-scurtu** [ember-cli/ember-cli#3906]
I've only tried this in an addon environment. 

Step 1: `ember generate blueprint foo-test`
Step 2: Visit `/tests`
Step 3: TestLoader Failures: dummy/blueprints/foo-test: could not be loaded

![screen shot 2015-04-15 at 12 00 44 pm](https://cloud.githubusercontent.com/assets/5492517/7155398/1684e1f2-e367-11e4-81ad-37774c47417a.png)

***Update*** It also happens in an app environment.

**Comment by stefanpenner** [comment]
I believe this was fixed on master, are you able to check?

**Comment by mihai-scurtu** [comment]
I'm not sure how to install master.. I did `npm i git+https://github.com/ember-cli/ember-cli.git` and I'm still getting the error.

**Comment by mihai-scurtu** [comment]
Still getting it on master.

**Comment by stefanpenner** [comment]
@marcioj this seems related to you fix, care to chime in?

**Comment by marcioj** [comment]
Looks like build/rebuild isn't consistent. Using the ember-cli master:

Scenario 1:
ember addon ember-simple-validate
npm link ember-cli
ember s
ember g initializer foo
// tests crashes with the error above
// restarting the server make them pass

**Comment by mihai-scurtu** [comment]
I will test that when I get in tomorrow morning.
