### ISSUE TITLE
ember install from private git repository

### ISSUE THREAD

**Issue by olivierlesnicki** [ember-cli/ember-cli#4077]
Can't use command ember install against private git repository.

This means I need to do npm install and run the default generator manually.

**Comment by stefanpenner** [comment]
ya this would be a good addition

**Comment by stefanpenner** [comment]
@rodyhaddad this one may be of interest to you

**Comment by vitch** [comment]
Where is the private git repository. You can successfully install from a private repository on GitHub over `git+ssh` e.g. 

```bash
ember install git+ssh://git@github.com:<repository-username>/<repository-name>.git#<optional-commitish>
```

**Comment by stefanpenner** [comment]
I am going to close this issue, as the above solution should solve the issue.

**Comment by olivierlesnicki** [comment]
We can't use ssh for security reasons ... only https.

**Comment by olivierlesnicki** [comment]
And while we can instlal the package over npm, the "default" blueprint generator is still not run.

**Comment by vitch** [comment]
You can ember install from an https URL as well e.g.

```bash
ember install https://github.com/<repository-username>/<repository-name>.git#<optional-commitish>
```

When I try that I get an authentication error but I presume you could [cache your password](https://help.github.com/articles/caching-your-github-password-in-git/) to avoid this.

**Comment by donahchoo** [comment]
@stefanpenner please reopen this since https does not work unless you cached your password.  if you have not cached your password you should get prompted for it.

**Comment by samselikoff** [comment]
I also think this should be reopened. While it does add the correct target to `package.json` and `npm installs` correctly, I came across two issues:

 - it uses the full target name to try to discover the install blueprint, which it fails to, displaying the following warning

    > WARNING: Could not figure out blueprint name from: "git+ssh://git@my-company.com:ui/nmbl-charts.git". Please install the addon blueprint via "ember generate <addon-name>" if necessary.

 - if I then manually run the install blueprint via `ember g nmbl-charts`, I hit another error since that blueprint tries to use `addAddonsToProject` with a target pointing to another private URL, which fails with "could not find addon with the name ____".

**Comment by brunowego** [comment]
@samselikoff same behavior here.
