### ISSUE TITLE
Future versions of Ember CLI will not support v4.0.0. Please update to Node 0.12 or io.js.

### ISSUE THREAD

**Issue by szines** [ember-cli/ember-cli#4814]
I've just updated node.js to 4.0 and it looks, ember cli would prefer 0.12 and will not support v4.0. :)

```
> ember s
Future versions of Ember CLI will not support v4.0.0. Please update to Node 0.12 or io.js.
version: 1.13.8
```

I assume this message for previous versions of node.js and not for the upcoming versions. :)

**Comment by trabus** [comment]
@szines I saw on slack that you're working on a PR, is this correct?

**Comment by stefanpenner** [comment]
we should loosen this, so don't have to patch every release :P

**Comment by szines** [comment]
@trabus Yes, I am on it. Just waiting for the test finish. ;)

**Comment by stefanpenner** [comment]
@szines :+1:

**Comment by xtagon** [comment]
Just to be clear, does Ember-CLI actually support Node v4 after all? Or do we really need to use Node 0.12 or io.js instead?

**Comment by stefanpenner** [comment]
> Just to be clear, does Ember-CLI actually support Node v4 after all? Or do we really need to use Node 0.12 or io.js instead?

ember-cli supports everything >=10 and 10 will be dropped soon.

**Comment by xtagon** [comment]
Thanks :)

**Comment by alekspetrov** [comment]
@stefanpenner, am I loose something? 

`ember -v                                      
Future versions of Ember CLI will not support v4.1.1. Please update to Node 0.12 or io.js.
version: 1.13.8
node: 4.1.1
npm: 2.13.4
os: darwin x64`

**Comment by H3Chief** [comment]
+1 still experiencing this issue on darwin. Node version I'm using is `4.1.0`

**Comment by stefanpenner** [comment]
> +1 still experiencing this issue on darwin. Node version I'm using is 4.1.0

its fixed on master, release hopefully in the next week.

**Comment by alekspetrov** [comment]
@stefanpenner thanks.

**Comment by fayimora** [comment]
:+1:

**Comment by matt3224** [comment]
Also seeing this issue

Matt$ ember -v
Future versions of Ember CLI will not support v4.2.1. Please update to Node 0.12 or io.js.
version: 1.13.8
node: 4.2.1
npm: 2.13.4
os: darwin x64

**Comment by rwjblue** [comment]
As mentioned above, this is fixed on master.  Our supported version detection was incorrect.

**Comment by sgentile** [comment]
Future versions of Ember CLI will not support v4.1.2. Please update to Node 0.12 or io.js.
version: 1.13.8
node: 4.1.2
npm: 2.13.4
os: darwin x64

Just ran npm install -g ember-cli

**Comment by haldiggs** [comment]
@sgentile yes I agree I am still seeing this, however since they closed the issue nobody will be seeing this.

**Comment by bitsapien** [comment]
I'm still seeing it. I'm using `node: 4.1.1`

**Comment by adambuczynski** [comment]
@stefanpenner Also still seeing it. Using Ember CLI 1.13.8:

```shell
Future versions of Ember CLI will not support v4.2.1. Please update to Node 0.12 or io.js.
version: 1.13.8
```

**Comment by szines** [comment]
This patch exists only in the #master branch, so it will disappear in Ember CLI 2.0 only as I know.

**Comment by andyklimczak** [comment]
Seeing with v5.0.0, ember cli 1.13.8

**Comment by stefanpenner** [comment]
> Ember CLI 2.0 only as I know.

1.13.9 and 2.x

**Comment by szines** [comment]
@stefanpenner Great news. Thanks for the update. Amazing. :)

**Comment by alvinkatojr** [comment]
Still getting the same error message with v5.0.0 and ember cli 1.13.8. Any update?

**Comment by szines** [comment]
@alvinkatojr Thanks for your comment. This patch will be released in v1.13.9 and v2.x

You can use the latest `#master` branch if you would like:

1. Clone this project in your computer.
2. `cd ember-cli`
3. `npm link`

In your active ember projects: `npm link ember-cli`

Npm link activate your local repository, so you can use the latest dev version of `ember-cli`.

**Comment by alvinkatojr** [comment]
Hi @szines! Thanks for the help. I am glad that to see that the Ember community is available and reliable in times like this! Keep it up and thanks again!

**Comment by HenryVonfire** [comment]
> Future versions of Ember CLI will not support v5.1.0. Please update to Node 0.12 or io.js.
v1.13.13

**Comment by stefanpenner** [comment]
> With the actual version 1.13.13
> 
> Future versions of Ember CLI will not support v5.1.0. Please update to Node 0.12 or io.js.

ug

**Comment by stefanpenner** [comment]
I was unable to reproduce this on master:

```
➜  ember-cli git:(master) ./bin/ember version
version: 1.13.13-master-c09f793c8a
node: 5.1.0
npm: 2.14.10
os: darwin x64
```
I have added additional tests to be sure: https://github.com/ember-cli/ember-cli/commit/72f446006fcdd90bb761d0a68e8308788a0ee065

Its worth noting, the NPM installed with node 5.1 is broken, cannot install itself nor ember-cli correctly. Its possible something else is going sideways on your machine?

**Comment by HenryVonfire** [comment]
Sorry, it was my bad. I had installed v1.13.13 but in the project I tested it, it was using v1.13.8.

**Comment by haldiggs** [comment]
just wondering if anyone will ever be updating the stock package on npm?
https://www.npmjs.com/package/ember-cli still pulls the older 1.13.8

**Comment by rwjblue** [comment]
1.13.13 is the latest (and is published to NPM).

**Comment by haldiggs** [comment]
sorry I'm relatively new to NPM but when I run
npm install ember-cli
or
npm update -g ember-cli@1.13.13
or
npm install -g ember-cli@1.13.13

I get 1.13.8 so maybe its my command thats jacked up

**Comment by stefanpenner** [comment]
@haldiggs sounds like you have a local cache issue? We published immediately and I (and our CI) confirms this

**Comment by haldiggs** [comment]
yes sir, it was my bad... I had forgot to look at the local file system.

On Mon, Dec 7, 2015 at 5:54 PM, Stefan Penner <notifications@github.com>
wrote:

> @haldiggs <https://github.com/haldiggs> sounds like you have a local
> cache issue? We published immediately and I (and our CI) confirms this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli/issues/4814#issuecomment-162708874>
> .
>



-- 
Hal D. Diggs
<https://www.mcpvirtualbusinesscard.com/VBCServer/haldiggs/card> - "Non
sibi sed patriae" (Not for self, but for country)
Half of communications is listening, and you can't listen with your mouth.

**Comment by ayyoob786** [comment]
I get an error like this 
future versions of ember cli will not support v5.8.0. please update to node 0.12 or io.js.

please help me some one to fix this

**Comment by zoltan-nz** [comment]
@mhdayyoob it is an alert which was in old ember-cli, but you can ignore it. If you update your ember-cli to the latest, it will disappear. Update your ember-cli with `npm install -g ember-cli`, and update in your project also.

**Comment by mhdayyoob** [comment]
@zoltan-nz thankyou buddy

**Comment by mtheoryx** [comment]
@zoltan-nz I ran into this just today. Here is my env and how I am able to reproduce (→: is my prompt):

```bash
→: node -v && npm -v
v4.4.0
2.14.20
```

```bash
→: npm uninstall ember-cli -g
unbuild ember-cli@2.6.3
```

```bash
→: npm install -g ember-cli
```

Nice output from the install process (warnings about minimatch 2.0.10)...

```bash
→: ember --version
Future versions of Ember CLI will not support v4.4.0. Please update to Node 0.12 or io.js.
version: 0.2.7

A new version of ember-cli is available (2.6.3). To install it, type ember update.
node: 4.4.0
npm: 2.11.0
```

So, let's run `ember update`?

```bash
→: ember update
Future versions of Ember CLI will not support v4.4.0. Please update to Node 0.12 or io.js.
version: 0.2.7

A new version of ember-cli is available (2.6.3). To install it, type ember update.

A new version of ember-cli is available (2.6.3).
[?] Are you sure you want to update ember-cli? Yes
```

After this runs, I get the following output after what looks like several successful dependency installs:

```bash
Updating ember-cli...
There was an error – possibly a permissions issue. You may need to manually run npm install -g ember-cli.
Cannot set property 'ember-cli' of undefined
TypeError: Cannot set property 'ember-cli' of undefined
    at Class.<anonymous> (/usr/local/lib/node_modules/ember-cli/lib/tasks/update.js:71:40)
    at lib$rsvp$$internal$$tryCatch (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by nathanhammond** [comment]
@mtheoryx You're running the Ember CLI version per the project directory here:

```
→: ember --version
Future versions of Ember CLI will not support v4.4.0. Please update to Node 0.12 or io.js.
version: 0.2.7
```

That is the expected (and expectedly wrong) output for a 0.2.7 Ember CLI install. We fixed this bug in later releases. Keeping this issue closed. Thank you for the detailed description so that I could identify what was happening without us having to go back and forth!

(Update your Ember CLI dep inside of the project and the issue will resolve itself.)

**Comment by mtheoryx** [comment]
How would I update that? This was ember cli installed globally. How would I fix this with a global npm install of ember-cli?

I've tried npm cache clean, as well as bower cache clean. I'm not sure what is "sticking around" in my system that causes such a down-rev version of ember-cli to get installed.

**Comment by zoltan-nz** [comment]
Hi @mtheoryx! Update version numbers in `package.json` and `bower.json`. Of course, test your project with the new versions. You can follow these steps: http://yoember.com/emberjs/how-to-keep-your-ember-js-project-up-to-date/

**Comment by mtheoryx** [comment]
Thanks a bunch @zoltan-nz! Turns out it was npm trolling me with a very old version of ember-cli that wasn't removed after uninstall and npm cache clean. I got it all working now, cheers!

**Comment by sojimon** [comment]
`
WARNING: Node v7.4.0 has currently not been tested against Ember CLI and may result in unexpected behaviour.
`
