### ISSUE TITLE
Tests failing with Make sure your tests index.html includes "assets/tests.js".

### ISSUE THREAD

**Issue by mmahalwy** [ember-cli/ember-cli#5093]
After updating to ember-cli 1.13.12 my tests keep getting:

```
Uncaught Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js".
```

Index.html
```
<script src="assets/vendor.js"></script>
    <script src="assets/test-support.js"></script>
    <script src="assets/kabuto.js"></script>
    <script src="testem.js" integrity=""></script>
    <script src="assets/tests.js"></script>
    <script src="assets/test-loader.js"></script>
```

**Comment by meleyal** [comment]
Same issue here, @mmahalwy did you find a fix for this?

**Comment by ianwalter** [comment]
@mmahalwy @meleyal I fixed this by putting `<script src="assets/tests.js"></script>` into the `tests/index.html` but I think this issue should be re-opened because ember-cli doesn't add this when generating a new ember app using `ember new`.

**Comment by meleyal** [comment]
@ianwalter thanks, yeah I tried that, but I still get the error almost every reload when using the Chrome runner.

**Comment by Samsinite** [comment]
@meleyal I just ran into a similar issue, turned out that another dev accidentally left the caret in the package.json causing to to install the newest ember-cli version.

It read: `"ember-cli": "^1.13.8"` instead of `"ember-cli": "1.13.8"` causing `npm install` to install 1.13.12 of ember-cli.

**Comment by meleyal** [comment]
@Samsinite that's the issue - using the latest `ember-cli` (`1.13.12`) the tests break.

**Comment by meleyal** [comment]
Duplicate of #5110
