### ISSUE TITLE
Module import path error on Windows in production build.

### ISSUE THREAD

**Issue by KrisOlszewski** [ember-cli/ember-cli#5542]
Upgraded Ember (2.4.1), Ember Data (2.4.0) and, Ember CLI (2.4.0). Everything works great in development mode, but when I build in production it throws console error:

```Uncaught Error: Could not find module ember-data/-private\system\references\record imported from ember-data/-private/system/references```.

Since vendors and app are uglified I have no idea where to start. Any help?

**Comment by stefanpenner** [comment]
as outlined in the [contributing.md](https://github.com/ember-cli/ember-cli/blob/master/CONTRIBUTING.md#reporting-a-bug) can you also share:

* OS
* npm version

**Comment by KrisOlszewski** [comment]
@stefanpenner thank you, my bad.

Jenkins Server - Windows Server 2012 R2, Windows_NT 6.3.9600
Node - `v5.7.0`
NPM - `v3.6.0`
Ember `v2.4.1`
Ember Data - `v2.4.0`
Ember CLI - `v2.4.0`

The weird part is I can create a working production build on OS X with no issues. It could be a Windows thing.

**Comment by stefanpenner** [comment]
@KrisOlszewski is their a longer stack trace associated with that?

**Comment by KrisOlszewski** [comment]
@stefanpenner unfortunately no. Nothing loads on the screen. single error. See below.

![screen shot 2016-03-01 at 3 47 35 pm](https://cloud.githubusercontent.com/assets/2780894/13443099/25da7152-dfc5-11e5-8f63-75b3f6b4c185.png)

**Comment by KrisOlszewski** [comment]
@stefanpenner sent you an email with unminified and minified files. I appreciate all the help!

**Comment by stefanpenner** [comment]
Thanks, I suspect running https://github.com/babel/broccoli-babel-transpiler/blob/master/index.js#L117through https://github.com/stefanpenner/ensure-posix-path will sort out the issue.

```js
options.filename = ensurePosix( options.sourceMapName = options.sourceFileName = relativePath);
```

**Comment by stefanpenner** [comment]
hmm, actually I wonder if this hapening in babel

**Comment by luxferresum** [comment]
I have the same problem. Its definitely a windows thing. Multiple paths with `\\` instead of `/` in the `vendor.js`.

**Comment by KrisOlszewski** [comment]
Updated issue title since we narrowed it down to Windows machine and module path problem.

**Comment by luxferresum** [comment]
Okay, I tried to downgrade to Ember 2.3 and now I can reproduce it on that version as well. I'm on my old package.json and bower.json, and have done a `npm uninstall -g ember-cli;npm install -g ember-cli;npm cache clean`, deleted `node_modules`, `tmp`,`dist` and `bower_components` and then reinstalled everything. Still the same issue. Maybe a minor change? Because it definitely worked a few days ago on the same machine!

**Comment by KrisOlszewski** [comment]
@luxferresum same here. I downgraded to Ember CLI 2.3.0, Ember 2.3.1, Ember Data 2.3.3, and it still passes production build on Windows machine, but throws console error in browser. It might be one of Ember CLI dependencies.

**Comment by nfc036** [comment]
Same problem here in production build (Windows, ember-cli: 2.4.1, ember: 2.4.1, Ember Data: 2.4.0, jQuery: 2.2.1).

**Comment by stefanpenner** [comment]
looking abit closer at @KrisOlszewski output:

```
 cat vendor-d3796b386a9ad54f025fbc91c6021294.js  | js-beautify | grep 'define("ember-data'
```

we get two different types of output:

the on in error:
```js
    }), define("ember-data/-private/system/references", ["exports", "ember-data/-private\\system\\references\\record", "ember-data/-private\\system\\references\\belongs-to", "ember-data/-private\\system\\references\\has-many"], function(e, t, r, n) {
```
which is the result of relative imports [here](https://github.com/emberjs/data/blob/master/addon/-private/system/references.js#L1-L3)


one that works:

```js
    }), define("ember-data/-private/system/record-array-manager", ["exports", "ember", "ember-data/-private/system/record-arrays", "ember-data/-private/system/ordered-set"], function(e, t, r, n) {
```

which is the result of absolute imports [here](https://github.com/emberjs/data/blob/master/addon/-private/system/record-array-manager.js#L5-L12)

Which suggests the code that resolve relative to absolute imports is in error.

**Comment by stefanpenner** [comment]
issue is most likely this line: https://github.com/emberjs/data/blob/master/lib/babel-build.js#L30

**Comment by stefanpenner** [comment]
I believe I have a fix: https://github.com/emberjs/data/pull/4202 but I don't have a windows machine handy to confirm. Can someone here give it a whirl?

I believe on a windows machine update package.json's ember-data slot to be `"ember-data": "emberjs/data#fix-windows"`

**Comment by stefanpenner** [comment]
it also seems ember-data's tests don't correctly test their prod builds, I have opened a tracking issue for that https://github.com/emberjs/data/issues/4203

**Comment by KrisOlszewski** [comment]
@stefanpenner I gave it a try during build itself. See below.

```version: 2.4.0
BuildingBuilding.Building..Building...BuildingBuilding.Build failed.
File: adapter.js
The Broccoli Plugin: [Babel] failed with:
TypeError: adapter.js: resolveModuleSource is not a function
    at File.resolveModuleSource (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\index.js:343:39)
    at NodePath.enter (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\modules\lib\metadata.js:29:42)
    at NodePath.call (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\traversal\path\context.js:56:28)
    at NodePath.visit (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\traversal\path\context.js:90:8)
    at TraversalContext.visitMultiple (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\traversal\context.js:108:16)
    at TraversalContext.visit (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\traversal\context.js:146:19)
    at Function.traverse.node (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\traversal\index.js:76:17)
    at Object.traverse [as default] (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\traversal\index.js:55:14)
    at NodePath.traverse (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\traversal\path\index.js:163:23)
    at Constructor.getMetadata (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\modules\_default.js:129:22)

The broccoli plugin was instantiated at: 
    at Babel.Plugin (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\broccoli-persistent-filter\node_modules\broccoli-plugin\index.js:7:31)
    at Babel.Filter [as constructor] (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\node_modules\broccoli-persistent-filter\index.js:38:10)
    at new Babel (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\index.js:34:10)
    at Babel (D:\Jenkins\workspace\project-name\node_modules\ember-data\node_modules\broccoli-babel-transpiler\index.js:29:12)
    at module.exports (D:\Jenkins\workspace\project-name\node_modules\ember-data\lib\babel-build.js:41:10)
    at module.exports (D:\Jenkins\workspace\project-name\node_modules\ember-data\lib\stripped-build.js:44:10)
    at Class.module.exports.treeForAddon (D:\Jenkins\workspace\project-name\node_modules\ember-data\index.js:95:27)
    at Class._treeFor (D:\Jenkins\workspace\project-name\node_modules\ember-cli\lib\models\addon.js:322:31)
    at Class.treeFor (D:\Jenkins\workspace\project-name\node_modules\ember-cli\lib\models\addon.js:290:19)
    at D:\Jenkins\workspace\project-name\node_modules\ember-cli\lib\broccoli\ember-app.js:446:20```

**Comment by stefanpenner** [comment]
@KrisOlszewski oops, try again?

**Comment by KrisOlszewski** [comment]
@stefanpenner it passed thru build, but failed in the browser again. 

```Uncaught Error: Could not find module -private/system/references/record imported from ember-data/-private/system/references```

`vendors.js` Gist: https://gist.github.com/KrisOlszewski/f087f0ec139bc4294c26

**Comment by stefanpenner** [comment]
@KrisOlszewski ok, we are closer.

**Comment by stefanpenner** [comment]
@KrisOlszewski was that both dev and prod, or just prod ?

**Comment by KrisOlszewski** [comment]
@stefanpenner only tested on prod, I'll run dev.

**Comment by KrisOlszewski** [comment]
@stefanpenner dev works fine with `emberjs/data#fix-windows`, while prod throws console error.

**Comment by stefanpenner** [comment]
@KrisOlszewski I suspect it is an additional issue, will investigate

**Comment by stefanpenner** [comment]
@KrisOlszewski I have an idea, is it possible for you to ping me on google hangouts or the ember community slack chat?

**Comment by stefanpenner** [comment]
my guess is the path being passed to:  `require('amd-name-resolver').moduleResolve` is mixed with `\` and `/`

**Comment by stefanpenner** [comment]
I'll look into the follow up issue tonight on my windows box.

**Comment by stefanpenner** [comment]
have confirmed on my windows box, once https://github.com/chadhietala/amd-name-resolver/pull/4  is merged + released  https://github.com/emberjs/data/pull/4205 fully addresses this issues

**Comment by KrisOlszewski** [comment]
@stefanpenner perfect, thank you! I'll retest once Ember Data and Ember CLI release with updates.

**Comment by nfc036** [comment]
Production builds seems fixed with ember-cli 2.4.2 in combination with ember-data 2.4.0. Thanks!

**Comment by rwjblue** [comment]
Hmm, the folks in https://github.com/emberjs/data/pull/4205 suggest that it is not fixed...

@nfc036 - Can you chime in over there? We need to figure out what subset of versions works properly...

**Comment by KrisOlszewski** [comment]
I can confirm this is now fixed and working in production on Windows machine. Thank you for all the help! Feel free to close this issue when needed.

**Comment by stefanpenner** [comment]
@KrisOlszewski took some doing :P sorry for issue

**Comment by DonGiulio** [comment]
I'm having the same problem on tophost web server (www.tophost.it) I'm not sure what OS that is, but the project works on my local mac

`% ember -v
version: 2.4.2
node: 5.8.0
os: darwin x64`

here's the error I got: 

`vendor-c7862e3….js:formatted:36Uncaught Error: Could not find module `-private/system/references/record` imported from `ember-data/-private/system/references`n @ vendor-c7862e3….js:formatted:36i @ vendor-c7862e3….js:formatted:42a.reify @ vendor-c7862e3….js:formatted:117a.build @ vendor-c7862e3….js:formatted:131i @ vendor-c7862e3….js:formatted:43a.reify @ vendor-c7862e3….js:formatted:117a.build @ vendor-c7862e3….js:formatted:131i @ vendor-c7862e3….js:formatted:43a.reify @ vendor-c7862e3….js:formatted:117a.build @ vendor-c7862e3….js:formatted:131i @ vendor-c7862e3….js:formatted:43a.reify @ vendor-c7862e3….js:formatted:117a.build @ vendor-c7862e3….js:formatted:131i @ vendor-c7862e3….js:formatted:43a.reify @ vendor-c7862e3….js:formatted:117a.build @ vendor-c7862e3….js:formatted:131i @ vendor-c7862e3….js:formatted:43a.reify @ vendor-c7862e3….js:formatted:117a.build @ vendor-c7862e3….js:formatted:131i @ vendor-c7862e3….js:formatted:43requireModule @ vendor-c7862e3….js:formatted:148(anonymous function) @ vendor-c7862e3….js:formatted:47486e.default @ vendor-c7862e3….js:formatted:47484(anonymous function) @ ettando-ebb90ed….js:1a.exports @ vendor-c7862e3….js:formatted:98a.build @ vendor-c7862e3….js:formatted:131i @ vendor-c7862e3….js:formatted:43requireModule @ vendor-c7862e3….js:formatted:148(anonymous function) @ ettando-ebb90ed….js:4
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'frameUrl' of undefined
    at chrome-extension://kcahibnffhnnjcedflmchmokndkjnhpg/everypage.js:1230:40handler @ extensions::uncaught_exception_handler:8(anonymous function) @ extensions::uncaught_exception_handler:100EventImpl.dispatch_ @ extensions::event_bindings:376EventImpl.dispatch @ extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94dispatchOnDisconnect @ extensions::messaging:306`

**Comment by stefanpenner** [comment]
@DonGiulio different issue then what was reported here
