### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by accelortech** [ember-cli/ember-cli#6595]
I am trying to compile my Cordova code for iOS but somehow when I try to run "ember serve" in /app/www/ folder then I get this error:

```
(node:21854) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:21854) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
version: 0.1.7
Looks like you have a different program called watchman, falling back to NodeWatcher
Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
    at RegExp.test (native)
    at Symbol.hasOwnProperty (/Users/apple/Desktop/bob/we/source-code/code/app/www/node_modules/ember-cli/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:163:43)
    at /Users/apple/Desktop/bob/we/source-code/code/app/www/node_modules/6to5-core/node_modules/core-js/library.js:136:17
    at setToStringTag (/Users/apple/Desktop/bob/we/source-code/code/app/www/node_modules/6to5-core/node_modules/core-js/library.js:88:13)
    at /Users/apple/Desktop/bob/we/source-code/code/app/www/node_modules/6to5-core/node_modules/core-js/library.js:610:3
    at /Users/apple/Desktop/bob/we/source-code/code/app/www/node_modules/6to5-core/node_modules/core-js/library.js:614:2
    at Object.<anonymous> (/Users/apple/Desktop/bob/we/source-code/code/app/www/node_modules/6to5-core/node_modules/core-js/library.js:2101:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

Please suggest me how to fix this.

**Comment by Turbo87** [comment]
@accelortech it looks like you are running a really old version of Ember CLI (`0.1.7` according to your log). there has been a lot of progress in Ember CLI since that release and a lot of bugs were fixed. your best bet to fix this issue is to update Ember CLI to a more recent version and see if the issue still persists

**Comment by accelortech** [comment]
In my project's /app/www/ folder, I ran these commands:
sudo npm uninstall ember-cli
npm cache clean
sudo npm install ember-cli

But the issue remains the same.

**Comment by Turbo87** [comment]
what does `ember --version` say now?

**Comment by accelortech** [comment]
If I try to run the above command, I get this output:
```

(node:21923) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:21923) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
version: 0.1.7
Looks like you have a different program called watchman, falling back to NodeWatcher
(node:21923) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
node: 6.9.2
npm: 2.1.8
```

**Comment by Turbo87** [comment]
as you can see you are still running Ember CLI v0.1.7. you should try to update CLI starting at https://github.com/ember-cli/ember-cli/releases?after=v0.1.9 and working your way up to a more recent release
