### ISSUE TITLE
ETIMEDOUT analytics behind proxy

### ISSUE THREAD

**Issue by AlanFonderflick** [ember-cli/ember-cli#6659]
Hey guys,

I receive 4 consecutive ETIMEDOUT errors when launching ember-cli on Windows 7 x64. I guess it's because I'm behind a proxy, even if I set npm and bower config.

Errors disappear when I set `"disableAnalytics": true` in `.ember-cli`.
```
ember-cli: 2.10.0
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: win32 x64
3.10.8
```

**Comment by nathanhammond** [comment]
I'm not sure which version of Ember CLI we addressed this in, it's a transitive dep issue in `leek`. Can you `rm -rf node_modules` and reinstall? I'm closing under the assumption that will clear it up. If not, please respond here again and we'll investigate.

/cc @twokul

**Comment by twokul** [comment]
@AlanFonderflick please double check and we the issue still persist I will look into it. I believe I fixed in `leek`.
