### ISSUE TITLE
Fresh ember-cli addon not building on Travis

### ISSUE THREAD

**Issue by amk221** [ember-cli/ember-cli#7472]
`ember addon example --yarn`

...builds locally, and tests pass, but not on Travis.

Example repo: https://github.com/amk221/-ember-cli-addon-example
Example failure on Travis: https://travis-ci.org/amk221/-ember-cli-addon-example/jobs/309504888

```
not ok 1 Chrome - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Non-zero exit code: null
            Stderr: 
             [1130/132440.461370:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.
            
            
        Log: |
            { type: 'error', text: 'Error: Browser exited unexpectedly' }
            { type: 'error', text: 'Non-zero exit code: null' }
            { type: 'error',
              text: '[1130/132440.461370:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I\'m aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.\n' }
    ...
```

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
ember-cli: 2.17.0
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
os: darwin x64
5.5.1
1.3.2
```

**Comment by kellyselden** [comment]
I've seen these errors too. They appear to be intermittent Chrome + Travis issues, and a restart of the job fixes it. I'm not sure there's anything we can do to fix.

Can you verify a restart of the job fixes it? Then we can close.

**Comment by kellyselden** [comment]
This is probably what you are seeing https://github.com/travis-ci/travis-ci/issues/8836

Closing.

**Comment by amk221** [comment]
You can probably see here I have multiple addons that I've Restarted multiple times today, but now joy... https://travis-ci.org/amk221/

**Comment by kellyselden** [comment]
I'm willing to bet they fix it soon without requiring any changes. If this issue persists for a long time, then we should looking into what we can do to work around it.

**Comment by kellyselden** [comment]
On second thought, lets keep this open for visibility until it is fixed.

**Comment by Turbo87** [comment]
this has been fixed by now, closing.

**Comment by jrowlingson** [comment]
This has recently resurfaced in travis-ci/travis-ci#8836

We've switched to Firefox 57.0. This is a better option for us then white listing the sudo enabled CIDR blocks.

```
  # testem.js

  launch_in_ci: [ 'Firefox' ],
  launch_in_dev: [ 'Firefox' ],
  browser_args: {
    Firefox: {
      mode: 'ci',
      args: [ '-headless' ]
    }
  }
```

```
  # travis.yml

  addons:
    firefox: 57.0
```

**Comment by bgentry** [comment]
This is definitely still an issue. I had to switch ember-apollo-client to `sudo: "required"` in its `.travis.yml`.

Maybe reopen this issue until travis-ci/travis-ci#8836 is resolved?
